databases:
  - name: save_sense
    databaseName: save_sense
    user: save_sense_user

services:
  - type: web
    name: save_sense
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: save_sense
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
